"""Climate archive: the same calendar window at one point for the last N complete years.

One NASA POWER request covers all years. The archive gives the player the choice of
year, the historical reference for the same point and window (used before calling a
season anomalous), and the list of years that fit each level's weather situation.
"""

from collections import OrderedDict
from dataclasses import dataclass, field
from datetime import UTC, date, datetime
from typing import Any

from app.services import weather
from app.services.nasa_power import SOURCE, NasaPowerError, NasaPowerService
from app.services.weather import Season, Window

DEMO_SOURCE = "Demo: synthetic weather generated by Farm Navigator (not NASA data, not a real place or year)"
DEMO_ELEVATION_M = 500.0


@dataclass
class Archive:
    latitude: float
    longitude: float
    window: Window
    status: str  # live | cached | demo
    source: str
    fetched_at: datetime
    request_url: str | None
    elevation_m: float
    parameter_info: dict[str, dict[str, Any]]
    time_standard: str
    community: str
    first_year: int
    latest_year: int
    seasons: dict[int, Season]
    stale: bool = False
    error: str | None = None
    messages: list[str] = field(default_factory=list)

    @property
    def is_demo(self) -> bool:
        return self.status == "demo"

    def complete_years(self) -> list[int]:
        return [y for y, s in sorted(self.seasons.items()) if s.complete]

    def season(self, year: int) -> Season:
        s = self.seasons.get(year)
        if s is None:
            raise KeyError(year)
        return s

    def provenance(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "stale": self.stale,
            "stale_reason": self.error,
            "source": self.source,
            "fetched_at": self.fetched_at.isoformat(),
            "request_url": self.request_url,
            "time_standard": self.time_standard,
            "community": self.community,
            "location": {
                "latitude": self.latitude,
                "longitude": self.longitude,
                "elevation_m": round(self.elevation_m),
            },
            "parameters": self.parameter_info,
            "window": {
                "start_md": f"{self.window.start_md[0]:02d}-{self.window.start_md[1]:02d}",
                "end_md": f"{self.window.end_md[0]:02d}-{self.window.end_md[1]:02d}",
                "crosses_year": self.window.crosses_year,
                "days": self.window.days(),
            },
            "years": {"first": self.first_year, "latest_complete": self.latest_year},
            "messages": self.messages,
        }


_ARCHIVES: OrderedDict[tuple[Any, ...], Archive] = OrderedDict()
_MAX_ARCHIVES = 64


def year_range(window: Window, today: date, model: dict[str, Any]) -> tuple[int, int]:
    cfg = model["data"]
    latest = weather.latest_complete_year(window, today, cfg["data_lag_days"])
    first = max(cfg["first_year"], latest - cfg["archive_years"] + 1)
    return first, latest


async def load_archive(
    service: NasaPowerService,
    latitude: float,
    longitude: float,
    window: Window,
    model: dict[str, Any],
    today: date,
    demo: bool = False,
) -> Archive:
    cfg = model["data"]
    first, latest = year_range(window, today, model)
    start = window.dates(first)[0]
    end = window.dates(latest)[1]
    params: list[str] = list(cfg["parameters"])

    if demo:
        key: tuple[Any, ...] = ("demo", round(latitude, 4) < 0, window, first, latest)
        cached = _ARCHIVES.get(key)
        if cached:
            return cached
        series = weather.demo_series(params, start, end, latitude)
        archive = Archive(
            latitude,
            longitude,
            window,
            "demo",
            DEMO_SOURCE,
            datetime.now(UTC).replace(microsecond=0),
            None,
            DEMO_ELEVATION_M,
            {p: {"units": weather.PARAM_UNITS_FALLBACK[p], "longname": p} for p in params},
            cfg["time_standard"],
            cfg["community"],
            first,
            latest,
            {},
        )
    else:
        response = await service.fetch(latitude, longitude, start, end, params, cfg["community"], cfg["time_standard"])
        key = ("power", response.request_url, response.fetched_at)
        cached = _ARCHIVES.get(key)
        if cached:
            cached.status, cached.stale, cached.error = response.status, response.stale, response.error
            return cached
        series = weather.normalize_power(response.parameter, params, start, end)
        info = {}
        for p in params:
            meta = response.parameter_info.get(p, {"units": "", "longname": ""})
            expected = weather.PARAM_UNITS_FALLBACK[p]
            unit_ok = meta["units"] == expected
            if not unit_ok:
                if p in cfg["required_parameters"]:
                    raise NasaPowerError(f"{p} came in '{meta['units']}', expected '{expected}'", "format")
                series.values[p] = [None] * len(series.dates)  # disable the mechanics that depend on it
            info[p] = {**meta, "available": unit_ok and p in response.parameter}
        archive = Archive(
            latitude,
            longitude,
            window,
            response.status,
            SOURCE,
            response.fetched_at,
            response.request_url,
            response.elevation_m if response.elevation_m is not None else 0.0,
            info,
            cfg["time_standard"],
            cfg["community"],
            first,
            latest,
            {},
            stale=response.stale,
            error=response.error,
            messages=response.messages,
        )

    for year in range(first, latest + 1):
        archive.seasons[year] = weather.build_season(series, year, window, latitude, archive.elevation_m, model)
    if not archive.complete_years():
        raise NasaPowerError("no complete season in the downloaded period", "incomplete")
    _ARCHIVES[key] = archive
    while len(_ARCHIVES) > _MAX_ARCHIVES:
        _ARCHIVES.popitem(last=False)
    return archive


def season_report(archive: Archive, year: int, model: dict[str, Any], with_daily: bool = False) -> dict[str, Any]:
    """A season as the API shows it: measured-data summary, features, reference comparison, season name."""
    s = archive.season(year)
    ref = weather.reference_stats(list(archive.seasons.values()), exclude_year=year)
    an = model["anomaly"]
    out = s.summary()
    out["season_name"] = weather.season_name(archive.latitude, s.start, s.end)
    out["hemisphere"] = "north" if archive.latitude >= 0 else "south"
    out["reference"] = ref
    out["anomaly"] = weather.anomalies(s, ref, an["min_reference_years"], an["z_threshold"])
    if with_daily:
        out["daily"] = s.daily()
    return out
